// Generated with Shader Minifier 1.3.6 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "v"
# define VAR_iFrame "y"
# define VAR_iResolution "m"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0) out vec4 v;"
 "layout(location=0) uniform vec4 m;"
 "layout(location=1) uniform int y;"
 "const float x=acos(-1.),a=x+x;\n"
 "#define saturate(x)clamp(x,0.0,1.0)\n"
 "#define linearstep(a,b,x)min(max(((x)-(a))/((b)-(a)),0.0),1.0)\n"
 "uvec3 i;"
 "vec3 s(vec3 v)"
 "{"
   "uvec3 y=floatBitsToUint(v);"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "return vec3(y)/float(-1u);"
 "}"
 "vec2 f(float v)"
 "{"
   "return vec2(cos(v),sin(v));"
 "}"
 "mat3 t(vec3 v)"
 "{"
   "v=normalize(v);"
   "vec3 x=abs(v.y)<.99?"
     "vec3(0,1,0):"
     "vec3(0,0,1),y=normalize(cross(x,v));"
   "return mat3(y,cross(v,y),v);"
 "}"
 "vec3 p(vec2 v)"
 "{"
   "vec2 y=floor(v),m=fract(v),x=m*m*m*(m*(m*6.-15.)+10.),i;"
   "vec3 z,r=vec3(0);"
   "int d=0;"
   "i=vec2(ivec2(d++)>>ivec2(0,1)&1);"
   "z=a*s(mod((y+i).xxy,256.));"
   "r+=mix(1.-x,x,i).x*mix(1.-x,x,i).y*(m-i).xxy*mat3(vec3(0,f(z.x)),vec3(0,f(z.y)),vec3(0,f(z.z)));"
   "i=vec2(ivec2(d++)>>ivec2(0,1)&1);"
   "z=a*s(mod((y+i).xxy,256.));"
   "r+=mix(1.-x,x,i).x*mix(1.-x,x,i).y*(m-i).xxy*mat3(vec3(0,f(z.x)),vec3(0,f(z.y)),vec3(0,f(z.z)));"
   "i=vec2(ivec2(d++)>>ivec2(0,1)&1);"
   "z=a*s(mod((y+i).xxy,256.));"
   "r+=mix(1.-x,x,i).x*mix(1.-x,x,i).y*(m-i).xxy*mat3(vec3(0,f(z.x)),vec3(0,f(z.y)),vec3(0,f(z.z)));"
   "i=vec2(ivec2(d++)>>ivec2(0,1)&1);"
   "z=a*s(mod((y+i).xxy,256.));"
   "r+=mix(1.-x,x,i).x*mix(1.-x,x,i).y*(m-i).xxy*mat3(vec3(0,f(z.x)),vec3(0,f(z.y)),vec3(0,f(z.z)));"
   "return r;"
 "}"
 "vec3 n(vec3 v)"
 "{"
   "vec4 y=vec4(0);"
   "for(int i=0;i++<4;)"
     "v*=t(vec3(-1,2,-3)),v+=sin(v.yzx),y=(y+vec4(cross(sin(v.zxy),cos(v)),1))/.5,v*=2.;"
   "return y.xyz/y.w;"
 "}"
 "vec3 f(vec2 v,vec2 x,float y)"
 "{"
   "vec2 z=abs(v)-x;"
   "float i=max(z.x,z.y);"
   "if(i>0.)"
     "{"
       "vec2 m=max(z,0.);"
       "float f=length(m);"
       "return vec3(sign(v)*m/f,f-y);"
     "}"
   "return vec3(sign(v)*step(vec2(i),z),i-y);"
 "}"
 "vec4 n(vec3 v,vec3 x,vec3 y)"
 "{"
   "float i=-dot(v,y)/dot(x,y);"
   "return i<0.?"
     "vec4(30):"
     "vec4(y,i);"
 "}"
 "vec4 p(vec3 x,vec3 v,vec3 y)"
 "{"
   "vec3 m=-x/v,i=abs(y/v),z=m-i,f=m+i;"
   "float w=max(max(z.x,z.y),z.z),a=min(min(f.x,f.y),f.z);"
   "return a<w?"
     "vec4(30):"
     "w>0.?"
       "vec4(-sign(v)*step(vec3(w),z),w):"
       "a>0.?"
         "vec4(-sign(v)*step(f,vec3(a)),a):"
         "vec4(30);"
 "}"
 "vec4 s(vec3 v,vec3 x,float y)"
 "{"
   "float m=dot(v,x),i=m*m-dot(v,v)+y*y;"
   "if(i<0.)"
     "return vec4(30);"
   "i=sqrt(i);"
   "float z=-m-i;"
   "if(z>0.)"
     "return vec4(normalize(v+x*z),z);"
   "z=-m+i;"
   "return z>0.?"
     "vec4(-normalize(v+x*z),z):"
     "vec4(30);"
 "}"
 "vec4 f(vec3 v,vec3 x,vec3 y,float i)"
 "{"
   "float m=dot(y,y),z=dot(y,x),f=dot(v,y),a=m-z*z,d=m*dot(v,x)-f*z,w=d*d-a*(m*dot(v,v)-f*f-i*i*m);"
   "if(w<0.)"
     "return vec4(30);"
   "float n=(-d-sqrt(w))/a;"
   "if(n<0.)"
     "return vec4(30);"
   "float l=clamp(f+n*z,0.,m);"
   "return l>0.&&l<m?"
     "vec4((v+x*n-l/m*y)/i,n):"
     "s(v-clamp(l,0.,m)/m*y,x,i);"
 "}"
 "float d(vec3 v)"
 "{"
   "v+=.2*n(2.*v);"
   "return length(v)-.75;"
 "}"
 "void main()"
 "{"
   "v*=0.;"
   "vec2 x=gl_FragCoord.xy/m.xy,z=x-.5;"
   "z.x*=m.x/m.y;"
   "vec3 i=s(vec3(z,y));"
   "for(int r=0;r++<10;)"
     "{"
       "vec2 l=z+(i=s(i)).xy/m.y;"
       "vec3 w=vec3(0,1.6,14),e=normalize(vec3(l,-4)),c=w+e*13.;"
       "w+=.01*vec3(f(a*(i=s(i)).x)*sqrt(i.y),0);"
       "e=normalize(c-w);"
       "vec3 b=vec3(2.-length(z));"
       "for(int u=0;u++<8;)"
         "{"
           "mat3 k;"
           "vec4 D=vec4(30),g,A;"
           "g=n(w-vec3(1,0,0),e,vec3(-1,0,0));"
           "A=n(w-vec3(0,0,-3),e,vec3(0,0,1));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=p(w-vec3(-2.5,0,4),e,vec3(1,10,1));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "if(g.w<D.w)"
             "D=g,k=mat3(1.);"
           "g=n(w,e,vec3(0,1,0));"
           "if(g.w<D.w)"
             "D=g,k=mat3(1.);"
           "g=n(w-vec3(0,3,0),e,vec3(0,-1,0));"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=abs(o.x+.5)<1.&&(abs(o.z)<.2||abs(o.z-12.)<.2)?"
                 "mat3(vec3(.3),vec3(4),vec3(.04,1,0)):"
                 "abs(o.x+.5)<1.03&&abs(o.z)<.23?"
                   "mat3(vec3(.8),vec3(0),vec3(.1,1,0)):"
                   "mat3(1.);"
             "}"
           "g=s(w-vec3(.8,3,-2),e,.1);"
           "if(g.w<D.w)"
             "D=g,k=mat3(vec3(.2),vec3(0),vec3(.04,1,0));"
           "w-=vec3(-1.4,1.5,-3);"
           "g=p(w,e,vec3(.6,1.2,.1));"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=abs(o.x)<.55&&abs(o.y)<1.15?"
                 "mat3(vec3(o),vec3(0),vec3(2)):"
                 "mat3(vec3(.8),vec3(0),vec3(.1,1,0));"
             "}"
           "w+=vec3(-1.4,1.5,-3);"
           "w-=vec3(1,1.8,2.5);"
           "g=p(w-vec3(0,0,-1.8),e,vec3(.05,.6,.05));"
           "A=p(w-vec3(0,0,1.8),e,vec3(.05,.6,.05));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=p(w-vec3(0,.6,0),e,vec3(.05,.05,1.85));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=p(w-vec3(0,-.6,0),e,vec3(.05,.05,1.85));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=abs(o.y)<.6&&abs(o.z)<1.8&&D.x==0.?"
                 "mat3(vec3(0),vec3(1),vec3(0,1,0)):"
                 "mat3(vec3(.8),vec3(0),vec3(.1,1,0));"
             "}"
           "g=p(w-vec3(-.049,0,0),e,vec3(0,.6,1.8));"
           "if(g.w<D.w)"
             "D=g,k=mat3(vec3(1),vec3(0),vec3(.04,0,6));"
           "g=p(w,e,vec3(.03,.6,1.8));"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=mat3(vec3(o),vec3(0),vec3(3));"
             "}"
           "w+=vec3(1,1.8,2.5);"
           "w-=vec3(-.1,2.7,2);"
           "g=p(w,e,vec3(.5,.2,.15));"
           "A=f(w-vec3(-.3,0,0),e,vec3(0,1,0),.05);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(.3,0,0),e,vec3(0,1,0),.05);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=abs(o.x)<.45&&abs(o.y)<.15&&o.z>0.?"
                 "mat3(vec3(o*4.),vec3(0),vec3(4)):"
                 "mat3(vec3(.1),vec3(0),vec3(.1,1,0));"
             "}"
           "w+=vec3(-.1,2.7,2);"
           "w-=vec3(.9,0,4);"
           "g=f(w-vec3(0,.85,0),e,vec3(0,0,20),.02);"
           "A=f(w-vec3(0,.85,0),e,vec3(1,0,0),.02);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.8,.3),e,vec3(2,-1,0),.012);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.8,.3),e,vec3(0,.05,0),.012);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.65,0),e,vec3(0,0,20),.02);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.65,0),e,vec3(1,0,0),.02);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.6,.3),e,vec3(2,-1,0),.012);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.6,.3),e,vec3(0,.05,0),.012);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "if(g.w<D.w)"
             "D=g,k=mat3(vec3(.8),vec3(0),vec3(.1,1,0));"
           "w+=vec3(.9,0,4);"
           "w-=vec3(0,1.6,-1);"
           "g=s(w,e,.9);"
           "if(g.w<D.w)"
             "{"
               "vec3 o=w;"
               "float B;"
               "for(int C=0;C++<30;)"
                 "B=.8*d(o),o+=B*e;"
               "if(abs(B)<.01)"
                 "{"
                   "vec2 C=vec2(0,.001);"
                   "D=vec4(normalize(vec3(d(o+C.yxx)-d(o-C.yxx),d(o+C.xyx)-d(o-C.xyx),d(o+C.xxy)-d(o-C.xxy))),length(w-o));"
                   "k=mat3(vec3(.6,.68,.7),vec3(0),vec3(.02,1,5));"
                 "}"
             "}"
           "w+=vec3(0,1.6,-1);"
           "if(D.w>29.)"
             "break;"
           "vec3 o=w+e*D.w;"
           "if(k[2].z==1.)"
             "{"
               "mat3 B=t(D.xyz);"
               "vec3 C=B*o;"
               "if(D.y==-1.)"
                 "{"
                   "float E=floor(o.z),F=o.z-E-.5;"
                   "if(abs(F)<.48)"
                     "k=mat3(vec3(.8),vec3(0),vec3(.2,0,0)),D.xyz=normalize(vec3(0,-1,.1*F)+.1*p(C.xy+4.*E));"
                   "else"
                     " k=mat3(vec3(.02),vec3(0),vec3(.8,0,0));"
                 "}"
               "else if(D.y==1.)"
                 "{"
                   "C.x+=.6;"
                   "vec2 E=mod(C.xy,.4)-.2;"
                   "vec3 F=f(E,vec2(.18),.01),G=floor(C/.4)+vec3(0,6,0),H=s(G);"
                   "C.x-=.6;"
                   "vec3 I=vec3(30);"
                   "if(floor(G.x/2.)==0.&&floor(G.y/2.)==0.)"
                     "I=f(mod(E-.035,.07)-.035,vec2(.01),.01);"
                   "else if(G.x==0.&&G.y>0.||G.y==0.&&G.x>0.)"
                     "{"
                       "vec2 J=G.x==0.?"
                         "E:"
                         "E.yx;"
                       "J.x=mod(J.x,.09)-.045;"
                       "I=f(J,vec2(0,.14),.03);"
                     "}"
                   "k=I.z<30.?"
                     "mat3(vec3(.8,.4,.1),vec3(0),vec3(.2,0,0)):"
                     "(E=mod(C.xy,.5)-.25,F=f(E,vec2(.235),.01),H=s(floor(C/.5)),mat3(mix(vec3(.1),vec3(.7),pow(s(floor(64.*mod(C.xyy,1.))).x,.2)),vec3(0),vec3(.4,0,0)));"
                   "if(F.z>0.)"
                     "k=mat3(vec3(.02),vec3(0),vec3(.8,0,0));"
                   "D.xyz=normalize(vec3(step(abs(I.z+.005),.005)*I.xy+step(abs(F.z+.002),.002)*F.xy+.01*p(40.*C.xy).xy+.02*(H.xy-.5),1)*B);"
                 "}"
               "else if(o.y>2.8)"
                 "k=mat3(vec3(.04,.04,.4),vec3(0),vec3(.2,0,0));"
               "else if(o.y<.2)"
                 "k=mat3(vec3(.1),vec3(0),vec3(.4,0,0));"
               "else"
                 "{"
                   "vec3 F=f(mod(C.xy,.1)-.05,vec2(.043),.003),G=s(floor(C.xyy/.1));"
                   "k=mat3(vec3(.02),vec3(0),vec3(.5,0,0));"
                   "if(F.z<0.)"
                     "k=mat3(vec3(.7,.74,.8),vec3(0),vec3(.14,0,0)),D.xyz=normalize(B*vec3(step(abs(F.z+.002),.002)*F.xy+.01*p(40.*C.xy).xy+.03*(G.xy-.5),1));"
                 "}"
             "}"
           "else if(k[2].z==2.)"
             "{"
               "vec2 C=k[0].xy*2.5;"
               "C.x-=clamp(floor(C.x),-1.,0.)+.53;"
               "vec2 F=C;"
               "F.y=abs(F.y)-.4;"
               "F-=sign(F)*min(abs(F),.1);"
               "F.x=min(F.x,0.);"
               "bool B=abs(length(F)-.3)<.1&&C.x<.35||abs(C.x-.25)<.1&&C.y>-.7&&C.y<.4;"
               "vec3 E=B?"
                 "vec3(1,.2,0):"
                 "vec3(1);"
               "F=k[0].xy;"
               "E*=exp2(2.*sin(6.*F.x)*sin(6.*F.x)*cos(F.y)*cos(F.y)-2.);"
               "k=mat3(vec3(.3),E,vec3(.01,1,0));"
             "}"
           "else if(k[2].z==3.)"
             "{"
               "vec2 C=k[0].yz*2.,F=floor(C+.5);"
               "C-=F;"
               "vec3 G=s(vec3(F.xyy));"
               "C=G.x<.5?"
                 "C:"
                 "-C;"
               "C=G.y<.5?"
                 "C:"
                 "C.yx;"
               "k=mat3(abs(C.x)<.25&&abs(C.y+.18)<.18||abs(C.x)<-C.y+.42&&C.y>0.?"
                 "F==vec2(0)?"
                   "vec3(1,.1,.4):"
                   "vec3(.01,.01,.2):"
                 "vec3(1),vec3(0),vec3(.5,0,0));"
             "}"
           "else if(k[2].z==4.)"
             "{"
               "bool C=false;"
               "vec2 F=k[0].xy;"
               "{"
                 "vec2 G=F;"
                 "G.y=abs(G.y);"
                 "C=C||abs(G.x-G.y+1.5)<.1&&G.y<.4||abs(G.x+1.1)<.4&&G.y<.1;"
               "}"
               "{"
                 "vec2 G=F;"
                 "G.x=abs(G.x+.25);"
                 "C=C||G.x<.05&&abs(G.y-.02)<.48||G.x<.22&&abs(G.y-.12)<.07||G.x<.24&&abs(G.y+.39)<.07||abs(G.x-.17)<.05&&abs(G.y-.23)<.21||abs(G.x-.19)<.05&&abs(G.y+.26)<.24;"
               "}"
               "{"
                 "vec2 G=F;"
                 "G.x=abs(G.x-.25);"
                 "C=C||G.x<.22&&abs(G.y-.28-.14)<.07||G.x<.22&&abs(G.y+.21-.14)<.07||abs(G.x-.17)<.05&&abs(G.y-.14)<.35;"
               "}"
               "{"
                 "vec2 G=F;"
                 "G.y=abs(G.y+.36);"
                 "C=C||abs(G.x-.04)<.02&&abs(G.y)<.13||abs(G.x-.08)<.05&&G.y<.02||abs(G.x-.08)<.06&&abs(G.y-.11)<.02;"
               "}"
               "{"
                 "vec2 G=abs(F-vec2(.23,-.36));"
                 "C=C||abs(G.x-.4*G.y)<.02&&abs(G.y)<.13;"
               "}"
               "C=C||abs(F.x-.34)<.02&&abs(F.y+.36)<.13;"
               "{"
                 "vec2 G=F;"
                 "G.x=abs(G.x-.44);"
                 "C=C||G.x<.02&&abs(G.y+.36)<.13||G.x<.06&&abs(G.y+.25)<.02;"
               "}"
               "k=mat3(vec3(.3),C?"
                 "vec3(2,2,0):"
                 "vec3(0),vec3(.1,1,0));"
             "}"
           "if(k[2].z!=5.)"
             "{"
               "vec3 G=w+e*D.w;"
               "float C=.2*smoothstep(0.,1.,n(G).x);"
               "k[2].x=mix(k[2].x,1.,C);"
               "C=smoothstep(-.5,.5,n(2.*G).x-G.y);"
               "k[0]=mix(k[0],vec3(0),C);"
               "k[1]=mix(k[1],vec3(0),C);"
               "k[2].x=mix(k[2].x,.04,C);"
             "}"
           "w=o+D.xyz*.001;"
           "float C=k[2].x*k[2].x,F=C*C;"
           "\n#ifdef DEBUG_NORMAL\n"
           "v=vec4(.5+.5*D.xyz,1);"
           "return;"
           "\n#endif\n"
           "{"
             "float G=clamp(dot(D.xyz,-e),0.,1.),E=mix(.04,1.,pow(1.-G,5.)),B=max(step((i=s(i)).x,E),k[2].y);"
             "v.xyz+=clamp(b,0.,4.)*(1.-E)*k[1];"
             "i.y=sqrt((1.-i.y)/(1.-B*(1.-F)*i.y));"
             "vec3 I=t(D.xyz)*vec3(sqrt(1.-i.y*i.y)*sin(a*i.z+vec2(0,a/4.)),i.y);"
             "if(B>0.)"
               "{"
                 "float J=clamp(dot(D.xyz,reflect(e,I)),0.,1.),H=clamp(dot(D.xyz,I),0.,1.),K=clamp(dot(-e,I),0.,1.),L=.5*C;"
                 "b*=J>0.&&H>0.?"
                   "mix(mix(vec3(.04),k[0],k[2].y),vec3(1),pow(1.-K,5.))/mix(E,1.,k[2].y)*J/(J*(1.-L)+L)/(G*(1.-L)+L)*K/H:"
                   "vec3(0);"
                 "I=reflect(e,I);"
               "}"
             "else"
               "{"
                 "if(dot(I,D.xyz)<0.)"
                   "break;"
                 "b*=(1.-mix(.04,1.,pow(1.-clamp(dot(-e,normalize(-e+I)),0.,1.),5.)))/(1.-E)*k[0];"
                 "if(k[2].z==6.)"
                   "{"
                     "w-=.002*D.xyz;"
                     "continue;"
                   "}"
               "}"
             "e=I;"
           "}"
           "if(dot(b,b)<.01)"
             "break;"
         "}"
     "}"
   "v.w=float(10);"
 "}";

#endif // FRAG_DRAW_H_
