// Generated with Shader Minifier 1.3.6 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "v"
# define VAR_iFrame "y"
# define VAR_iResolution "m"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0) out vec4 v;"
 "layout(location=0) uniform vec4 m;"
 "layout(location=1) uniform int y;"
 "const float a=acos(-1.),x=a+a;\n"
 "#define saturate(x)clamp(x,0.0,1.0)\n"
 "#define linearstep(a,b,x)min(max(((x)-(a))/((b)-(a)),0.0),1.0)\n"
 "uvec3 i;"
 "vec3 s(vec3 v)"
 "{"
   "uvec3 y=floatBitsToUint(v);"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "return vec3(y)/float(-1u);"
 "}"
 "vec2 f(float v)"
 "{"
   "return vec2(cos(v),sin(v));"
 "}"
 "mat3 t(vec3 v)"
 "{"
   "v=normalize(v);"
   "vec3 y=abs(v.y)<.99?"
     "vec3(0,1,0):"
     "vec3(0,0,1),x=normalize(cross(y,v));"
   "return mat3(x,cross(v,x),v);"
 "}"
 "vec3 p(vec2 v)"
 "{"
   "vec2 y=floor(v),m=fract(v),z=m*m*m*(m*(m*6.-15.)+10.),i;"
   "vec3 a,r=vec3(0);"
   "int d=0;"
   "i=vec2(ivec2(d++)>>ivec2(0,1)&1);"
   "a=x*s(mod((y+i).xxy,256.));"
   "r+=mix(1.-z,z,i).x*mix(1.-z,z,i).y*(m-i).xxy*mat3(vec3(0,f(a.x)),vec3(0,f(a.y)),vec3(0,f(a.z)));"
   "i=vec2(ivec2(d++)>>ivec2(0,1)&1);"
   "a=x*s(mod((y+i).xxy,256.));"
   "r+=mix(1.-z,z,i).x*mix(1.-z,z,i).y*(m-i).xxy*mat3(vec3(0,f(a.x)),vec3(0,f(a.y)),vec3(0,f(a.z)));"
   "i=vec2(ivec2(d++)>>ivec2(0,1)&1);"
   "a=x*s(mod((y+i).xxy,256.));"
   "r+=mix(1.-z,z,i).x*mix(1.-z,z,i).y*(m-i).xxy*mat3(vec3(0,f(a.x)),vec3(0,f(a.y)),vec3(0,f(a.z)));"
   "i=vec2(ivec2(d++)>>ivec2(0,1)&1);"
   "a=x*s(mod((y+i).xxy,256.));"
   "r+=mix(1.-z,z,i).x*mix(1.-z,z,i).y*(m-i).xxy*mat3(vec3(0,f(a.x)),vec3(0,f(a.y)),vec3(0,f(a.z)));"
   "return r;"
 "}"
 "vec3 n(vec3 v)"
 "{"
   "vec4 y=vec4(0);"
   "for(int i=0;i++<4;)"
     "v*=t(vec3(-1,2,-3)),v+=sin(v.yzx),y=(y+vec4(cross(sin(v.zxy),cos(v)),1))/.5,v*=2.;"
   "return y.xyz/y.w;"
 "}"
 "vec3 f(vec2 v,vec2 z,float y)"
 "{"
   "vec2 x=abs(v)-z;"
   "float i=max(x.x,x.y);"
   "if(i>0.)"
     "{"
       "vec2 a=max(x,0.);"
       "float f=length(a);"
       "return vec3(sign(v)*a/f,f-y);"
     "}"
   "return vec3(sign(v)*step(vec2(i),x),i-y);"
 "}"
 "vec4 n(vec3 v,vec3 y,vec3 x)"
 "{"
   "float i=-dot(v,x)/dot(y,x);"
   "return i<0.?"
     "vec4(30):"
     "vec4(x,i);"
 "}"
 "vec4 p(vec3 v,vec3 y,vec3 x)"
 "{"
   "vec3 m=-v/y,z=abs(x/y),i=m-z,a=m+z;"
   "float f=max(max(i.x,i.y),i.z),w=min(min(a.x,a.y),a.z);"
   "return w<f?"
     "vec4(30):"
     "f>0.?"
       "vec4(-sign(y)*step(vec3(f),i),f):"
       "w>0.?"
         "vec4(-sign(y)*step(a,vec3(w)),w):"
         "vec4(30);"
 "}"
 "vec4 s(vec3 v,vec3 y,float x)"
 "{"
   "float m=dot(v,y),i=m*m-dot(v,v)+x*x;"
   "if(i<0.)"
     "return vec4(30);"
   "i=sqrt(i);"
   "float a=-m-i;"
   "if(a>0.)"
     "return vec4((v+y*a)/x,a);"
   "a=-m+i;"
   "return a>0.?"
     "vec4((-v-y*a)/x,a):"
     "vec4(30);"
 "}"
 "vec4 f(vec3 v,vec3 y,vec3 x,float z)"
 "{"
   "float m=dot(x,x),i=dot(x,y),a=dot(v,x),f=m-i*i,d=m*dot(v,y)-a*i,w=d*d-f*(m*dot(v,v)-a*a-z*z*m);"
   "if(w<0.)"
     "return vec4(30);"
   "float n=(-d-sqrt(w))/f,p=clamp(a+n*i,0.,m);"
   "return p>0.&&p<m?"
     "vec4((v-p/m*x+y*n)/z,n):"
     "s(v-p/m*x,y,z);"
 "}"
 "float d(vec3 v)"
 "{"
   "v+=.2*n(2.*v);"
   "return length(v)-.75;"
 "}"
 "void main()"
 "{"
   "v*=0.;"
   "vec2 a=gl_FragCoord.xy/m.xy,i=a-.5;"
   "i.x*=m.x/m.y;"
   "vec3 z=s(vec3(i,y));"
   "for(int r=0;r++<10;)"
     "{"
       "vec2 l=i+(z=s(z)).xy/m.y;"
       "vec3 w=vec3(0,1.6,14),e=normalize(vec3(l,-4)),c=w+e*13.;"
       "w+=.01*vec3(f(x*(z=s(z)).x)*sqrt(z.y),0);"
       "e=normalize(c-w);"
       "vec3 b=vec3(2.-length(i));"
       "for(int u=0;u++<8;)"
         "{"
           "mat3 k;"
           "vec4 D=vec4(30),g,A;"
           "g=n(w-vec3(1,0,0),e,vec3(-1,0,0));"
           "A=n(w-vec3(0,0,-3),e,vec3(0,0,1));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=p(w-vec3(-2.5,0,4),e,vec3(1,10,1));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "if(g.w<D.w)"
             "D=g,k=mat3(1.);"
           "g=n(w,e,vec3(0,1,0));"
           "if(g.w<D.w)"
             "D=g,k=mat3(1.);"
           "g=n(w-vec3(0,3,0),e,vec3(0,-1,0));"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=abs(o.x+.5)<1.&&(abs(o.z)<.2||abs(o.z-12.)<.2)?"
                 "mat3(vec3(.3),vec3(4),vec3(.04,1,0)):"
                 "abs(o.x+.5)<1.03&&abs(o.z)<.23?"
                   "mat3(vec3(.8),vec3(0),vec3(.1,1,0)):"
                   "mat3(1.);"
             "}"
           "w-=vec3(-1.4,1.5,-3);"
           "g=p(w,e,vec3(.6,1.2,.1));"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=abs(o.x)<.55&&abs(o.y)<1.15?"
                 "mat3(vec3(o),vec3(0),vec3(2)):"
                 "mat3(vec3(.8),vec3(0),vec3(.1,1,0));"
             "}"
           "w+=vec3(-1.4,1.5,-3);"
           "w-=vec3(1,1.8,2.5);"
           "g=p(w-vec3(0,0,-1.8),e,vec3(.05,.6,.05));"
           "A=p(w-vec3(0,0,1.8),e,vec3(.05,.6,.05));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=p(w-vec3(0,.6,0),e,vec3(.05,.05,1.85));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=p(w-vec3(0,-.6,0),e,vec3(.05,.05,1.85));"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=abs(o.y)<.6&&abs(o.z)<1.8&&D.x==0.?"
                 "mat3(vec3(0),vec3(1),vec3(0,1,0)):"
                 "mat3(vec3(.8),vec3(0),vec3(.1,1,0));"
             "}"
           "g=p(w-vec3(-.049,0,0),e,vec3(0,.6,1.8));"
           "if(g.w<D.w)"
             "D=g,k=mat3(vec3(1),vec3(0),vec3(.04,0,6));"
           "g=p(w,e,vec3(.01,.6,1.8));"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=mat3(vec3(o),vec3(0),vec3(3));"
             "}"
           "w+=vec3(1,1.8,2.5);"
           "w-=vec3(-.1,2.7,2);"
           "g=p(w,e,vec3(.5,.2,.15));"
           "A=f(w-vec3(-.3,0,0),e,vec3(0,1,0),.05);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(.3,0,0),e,vec3(0,1,0),.05);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "if(g.w<D.w)"
             "{"
               "D=g;"
               "vec3 o=w+e*D.w;"
               "k=abs(o.x)<.45&&abs(o.y)<.15&&o.z>0.?"
                 "mat3(vec3(o*4.),vec3(0),vec3(4)):"
                 "mat3(vec3(.1),vec3(0),vec3(.1,1,0));"
             "}"
           "w+=vec3(-.1,2.7,2);"
           "w-=vec3(.9,0,4);"
           "g=f(w-vec3(0,.85,0),e,vec3(0,0,20),.02);"
           "A=f(w-vec3(0,.85,0),e,vec3(1,0,0),.02);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.8,.3),e,vec3(1,-1,0),.012);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.8,.3),e,vec3(0,.05,0),.012);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.65,0),e,vec3(0,0,20),.02);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.65,0),e,vec3(1,0,0),.02);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.6,.3),e,vec3(1,-1,0),.012);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "A=f(w-vec3(0,.6,.3),e,vec3(0,.05,0),.012);"
           "g=g.w<A.w?"
             "g:"
             "A;"
           "if(g.w<D.w)"
             "D=g,k=mat3(vec3(.8),vec3(0),vec3(.1,1,0));"
           "w+=vec3(.9,0,4);"
           "w-=vec3(0,1.6,-1);"
           "g=s(w,e,.9);"
           "if(g.w<D.w)"
             "{"
               "vec3 o=w;"
               "float B;"
               "for(int C=0;C++<30;)"
                 "B=.8*d(o),o+=B*e;"
               "if(abs(B)<.01)"
                 "{"
                   "vec2 C=vec2(0,.001);"
                   "D=vec4(normalize(vec3(d(o+C.yxx)-d(o-C.yxx),d(o+C.xyx)-d(o-C.xyx),d(o+C.xxy)-d(o-C.xxy))),length(w-o));"
                   "k=mat3(vec3(.6,.68,.7),vec3(0),vec3(.02,1,5));"
                 "}"
             "}"
           "w+=vec3(0,1.6,-1);"
           "if(D.w>29.)"
             "break;"
           "vec3 o=w+e*D.w;"
           "if(k[2].z==1.)"
             "{"
               "mat3 B=t(D.xyz);"
               "vec3 C=B*o;"
               "if(D.y==-1.)"
                 "{"
                   "float E=floor(o.z),F=o.z-E-.5;"
                   "if(abs(F)<.48)"
                     "k=mat3(vec3(.8),vec3(0),vec3(.2,0,0)),D.xyz=normalize(vec3(0,-1,.1*F)+.1*p(C.xy+4.*E));"
                   "else"
                     " k=mat3(vec3(.02),vec3(0),vec3(.8,0,0));"
                 "}"
               "else if(D.y==1.)"
                 "{"
                   "C.x+=.6;"
                   "vec2 F=mod(C.xy,.4)-.2;"
                   "vec3 E=f(F,vec2(.18),.01),G=floor(C/.4)+vec3(0,6,0),H=s(G);"
                   "C.x-=.6;"
                   "vec2 I=F;"
                   "if(floor(G.x/2.)==0.&&floor(G.y/2.)==0.)"
                     "I=mod(I-.04,.08)-.04,k=mat3(vec3(.8,.4,.1),vec3(0),vec3(.2,0,0));"
                   "else if(G.x==0.&&G.y>0.||G.y==0.&&G.x>0.)"
                     "I=G.x==0.?"
                       "I:"
                       "I.yx,I.x=mod(I.x,.1)-.05,I.y-=clamp(I.y,-.15,.15),k=mat3(vec3(.8,.4,.1),vec3(0),vec3(.2,0,0));"
                   "if(I==F)"
                     "I+=1.,F=mod(C.xy,.5)-.25,E=f(F,vec2(.235),.01),H=s(floor(C/.5)),k=mat3(mix(vec3(.1),vec3(.7),pow(s(floor(64.*mod(C.xyy,1.))).x,.2)),vec3(0),vec3(.4,0,0));"
                   "if(E.z>0.)"
                     "k=mat3(vec3(.02),vec3(0),vec3(.8,0,0));"
                   "D.xyz=normalize(vec3((I==F?"
                     "vec2(0):"
                     "step(abs(length(I)-.025),.005)*normalize(I))+step(abs(E.z+.002),.002)*E.xy+.01*p(40.*C.xy).xy+.02*H.xy,1)*B);"
                 "}"
               "else if(o.y>2.8)"
                 "k=mat3(vec3(.04,.04,.4),vec3(0),vec3(.2,0,0));"
               "else if(o.y<.2)"
                 "k=mat3(vec3(.1),vec3(0),vec3(.4,0,0));"
               "else"
                 "{"
                   "vec3 I=f(mod(C.xy,.1)-.05,vec2(.043),.003),E=s(floor(C.xyy/.1));"
                   "k=mat3(vec3(.02),vec3(0),vec3(.5,0,0));"
                   "if(I.z<0.)"
                     "k=mat3(vec3(.7,.74,.8),vec3(0),vec3(.14,0,0)),D.xyz=normalize(B*vec3(step(abs(I.z+.002),.002)*I.xy+.01*p(40.*C.xy).xy+.03*E.xy,1));"
                 "}"
             "}"
           "else if(k[2].z==2.)"
             "{"
               "vec2 C=k[0].xy*2.5;"
               "C.x-=clamp(floor(C.x),-1.,0.)+.53;"
               "vec2 I=C;"
               "I.y=abs(I.y)-.4;"
               "I-=sign(I)*min(abs(I),.1);"
               "I.x=min(I.x,0.);"
               "bool F=abs(length(I)-.3)<.1&&C.x<.35||abs(C.x-.25)<.1&&C.y>-.7&&C.y<.4;"
               "vec3 E=F?"
                 "vec3(1,.2,0):"
                 "vec3(1);"
               "I=k[0].xy;"
               "E*=exp2(2.*sin(6.*I.x)*sin(6.*I.x)*cos(I.y)*cos(I.y)-2.);"
               "k=mat3(vec3(.3),E,vec3(.01,1,0));"
             "}"
           "else if(k[2].z==3.)"
             "{"
               "vec2 I=k[0].yz*2.,C=floor(I+.5);"
               "I-=C;"
               "vec3 E=s(vec3(C.xyy));"
               "I=E.x<.5?"
                 "I:"
                 "-I;"
               "I=E.y<.5?"
                 "I:"
                 "I.yx;"
               "k=mat3(abs(I.x)<.25&&abs(I.y+.18)<.18||abs(I.x)<-I.y+.42&&I.y>0.?"
                 "C==vec2(0)?"
                   "vec3(1,.1,.4):"
                   "vec3(.01,.01,.2):"
                 "vec3(1),vec3(0),vec3(.5,0,0));"
             "}"
           "else if(k[2].z==4.)"
             "{"
               "bool I=false;"
               "vec2 C=k[0].xy;"
               "{"
                 "vec2 E=C;"
                 "E.y=abs(E.y);"
                 "I=I||abs(E.x-E.y+1.5)<.1&&E.y<.4||abs(E.x+1.1)<.4&&E.y<.1;"
               "}"
               "{"
                 "vec2 E=C;"
                 "E.x=abs(E.x+.25);"
                 "I=I||E.x<.05&&abs(E.y-.02)<.48||E.x<.22&&abs(E.y-.12)<.07||E.x<.24&&abs(E.y+.39)<.07||abs(E.x-.17)<.05&&abs(E.y-.23)<.21||abs(E.x-.19)<.05&&abs(E.y+.26)<.24;"
               "}"
               "{"
                 "vec2 E=C;"
                 "E.x=abs(E.x-.25);"
                 "I=I||E.x<.22&&abs(E.y-.28-.14)<.07||E.x<.22&&abs(E.y+.21-.14)<.07||abs(E.x-.17)<.05&&abs(E.y-.14)<.35;"
               "}"
               "{"
                 "vec2 E=C;"
                 "E.y=abs(E.y+.36);"
                 "I=I||abs(E.x-.04)<.02&&abs(E.y)<.13||abs(E.x-.08)<.05&&E.y<.02||abs(E.x-.08)<.06&&abs(E.y-.11)<.02;"
               "}"
               "{"
                 "vec2 E=abs(C-vec2(.23,-.36));"
                 "I=I||abs(E.x-.4*E.y)<.02&&abs(E.y)<.13;"
               "}"
               "I=I||abs(C.x-.34)<.02&&abs(C.y+.36)<.13;"
               "{"
                 "vec2 E=C;"
                 "E.x=abs(E.x-.44);"
                 "I=I||E.x<.02&&abs(E.y+.36)<.13||E.x<.06&&abs(E.y+.25)<.02;"
               "}"
               "k=mat3(vec3(.3),I?"
                 "vec3(2,2,0):"
                 "vec3(0),vec3(.1,1,0));"
             "}"
           "if(k[2].z!=5.)"
             "{"
               "vec3 E=w+e*D.w;"
               "float I=.2*smoothstep(0.,1.,n(E).x);"
               "k[2].x=mix(k[2].x,1.,I);"
               "I=smoothstep(-.5,.5,n(2.*E).x-E.y);"
               "k[0]=mix(k[0],vec3(0),I);"
               "k[1]=mix(k[1],vec3(0),I);"
               "k[2].x=mix(k[2].x,.04,I);"
             "}"
           "w=o+D.xyz*.001;"
           "float I=k[2].x*k[2].x,E=I*I;"
           "\n#ifdef DEBUG_NORMAL\n"
           "v=vec4(.5+.5*D.xyz,1);"
           "return;"
           "\n#endif\n"
           "{"
             "float C=clamp(dot(D.xyz,-e),0.,1.),F=mix(.04,1.,pow(1.-C,5.)),B=max(step((z=s(z)).x,F),k[2].y);"
             "v.xyz+=clamp(b,0.,4.)*(1.-F)*k[1];"
             "z.y=sqrt((1.-z.y)/(1.-B*(1.-E)*z.y));"
             "vec3 G=t(D.xyz)*vec3(sqrt(1.-z.y*z.y)*sin(x*z.z+vec2(0,x/4.)),z.y);"
             "if(B>0.)"
               "{"
                 "float H=clamp(dot(D.xyz,reflect(e,G)),0.,1.),J=clamp(dot(D.xyz,G),0.,1.),K=clamp(dot(-e,G),0.,1.),L=.5*I;"
                 "b*=H>0.&&J>0.?"
                   "mix(mix(vec3(.04),k[0],k[2].y),vec3(1),pow(1.-K,5.))/mix(F,1.,k[2].y)*H/(H*(1.-L)+L)/(C*(1.-L)+L)*K/J:"
                   "vec3(0);"
                 "G=reflect(e,G);"
               "}"
             "else"
               "{"
                 "if(dot(G,D.xyz)<0.)"
                   "break;"
                 "b*=(1.-mix(.04,1.,pow(1.-clamp(dot(-e,normalize(-e+G)),0.,1.),5.)))/(1.-F)*k[0];"
                 "if(k[2].z==6.)"
                   "{"
                     "w-=.002*D.xyz;"
                     "continue;"
                   "}"
               "}"
             "e=G;"
           "}"
           "if(dot(b,b)<.01)"
             "break;"
         "}"
     "}"
   "v.w=float(10);"
 "}";

#endif // FRAG_DRAW_H_
